import React,{useMemo,useState}from"react";import{createRoot}from"react-dom/client";import ReactMarkdown from"react-markdown";import remarkGfm from"remark-gfm";import rehypeSanitize,{defaultSchema}from"rehype-sanitize";import{Search,Sun,Moon,Copy,Check,ShieldCheck,FileText}from"lucide-react";import"./styles.css";import md from"../public/test-cases.md?raw";
const schema={...defaultSchema,tagNames:[...(defaultSchema.tagNames||[]),"del"],attributes:{...defaultSchema.attributes,a:["href","title","target","rel"],code:["className"]},protocols:{...defaultSchema.protocols,href:["http","https","mailto"],src:["http","https"]}};
const slug=s=>String(s).toLowerCase().replace(/[^\w\s-]/g,"").trim().replace(/\s+/g,"-");
function structure(text){let out=[],cat=null,f=false;for(const l of text.split(/\r?\n/)){if(/^\s*```/.test(l)){f=!f;continue}if(f)continue;let c=l.match(/^## 🏷️ Category:\s*(.+)$/);if(c){cat={title:c[1].trim(),cases:[]};out.push(cat);continue}let t=l.match(/^### Test Case\s+(\d+):\s*(.+)$/);if(t&&cat)cat.cases.push({number:+t[1],title:t[2].trim()})}return out}
function Code({inline,className,children,...p}){const[ok,setOk]=useState(false),text=String(children).replace(/\n$/,"");if(inline)return <code className="inline-code" {...p}>{children}</code>;return <div className="code-wrap"><button className="copy" onClick={async()=>{try{await navigator.clipboard.writeText(text);setOk(true);setTimeout(()=>setOk(false),1200)}catch{}}}>{ok?<Check size={14}/>:<Copy size={14}/>} {ok?"Copied":"Copy"}</button><pre className={className||""}><code {...p}>{children}</code></pre></div>}
function Link({href,children,...p}){if(!/^(https?:|mailto:)/i.test(href||""))return <span>{children}</span>;return <a href={href} target="_blank" rel="noopener noreferrer nofollow" {...p}>{children}</a>}
const comps={code:Code,pre:({children})=><>{children}</>,a:Link,img:()=>null};
function App(){const[dark,setDark]=useState(true),[q,setQ]=useState(""),[raw,setRaw]=useState(false),s=useMemo(()=>structure(md),[]),f=useMemo(()=>{let x=q.toLowerCase().trim();if(!x)return s;return s.map(c=>({...c,cases:c.cases.filter(t=>(`${t.number} ${t.title} ${c.title}`).toLowerCase().includes(x))})).filter(c=>c.title.toLowerCase().includes(x)||c.cases.length)},[q,s]),total=s.reduce((n,c)=>n+c.cases.length,0);return <div className={dark?"app dark":"app"}><header><div className="brand"><div className="logo"><ShieldCheck size={22}/></div><div><b>Vulnerability Test Cases</b><small>Security Testing Documentation</small></div></div><div className="actions"><div className="search"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search test cases..."/></div><button className="theme" onClick={()=>setDark(!dark)}>{dark?<Sun size={18}/>:<Moon size={18}/>}</button></div></header><div className="layout"><aside><div className="summary"><div><FileText size={15}/> {total} Test Cases</div><small>{s.length} categories</small></div>{f.map(c=><section key={c.title}><button className="cat" onClick={()=>document.getElementById(slug("Category "+c.title))?.scrollIntoView({behavior:"smooth"})}>{c.title}</button>{c.cases.map(t=><button className="tc" key={t.number} onClick={()=>document.getElementById(slug(`Test Case ${t.number}: ${t.title}`))?.scrollIntoView({behavior:"smooth"})}><i>{t.number}</i>{t.title}</button>)}</section>)}</aside><main><div className="hero"><div><span>DOCUMENTATION</span><h1>Vulnerability Test Cases</h1><p>{total} test cases across {s.length} vulnerability categories.</p></div><div className="switch"><button className={!raw?"active":""} onClick={()=>setRaw(false)}>Rendered</button><button className={raw?"active":""} onClick={()=>setRaw(true)}>Raw Markdown</button></div></div><article>{raw?<pre className="raw">{md}</pre>:<ReactMarkdown remarkPlugins={[remarkGfm]} rehypePlugins={[[rehypeSanitize,schema]]} components={{...comps,h2:({children})=>{let t=String(children).replace(/^🏷️ Category:\s*/i,"");return <h2 id={slug("Category "+t)}>{children}</h2>},h3:({children})=>{let t=String(children);return <h3 id={slug(t)}>{children}</h3>}}}>{md}</ReactMarkdown>}</article></main></div></div>}
createRoot(document.getElementById("root")).render(<App/>);
